language: go

sudo: false

os:
  - linux
  - osx

go:
  - 1.11.x
  - 1.12.x
  - master

install:
 - go get -t ./...

script:
 - diff <(gofmt -d .) <(printf "")
 - go test -v -cpu=2 ./...
 - go test -cpu=1,2,4 -short -race ./...

matrix:
  allow_failures:
    - go: 'master'
  fast_finish: true  